language: c
sudo: required
install: 
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docgen.sh
script: 
  - bash -ex .travis-opam.sh
  - bash -ex .travis-docgen.sh
env:
  matrix:
  - OCAML_VERSION=4.03 OPAM_VERSION=1.2.2 TESTS=true MERLIN_TRAVIS=true INSTALL=true PACKAGE=toy BASE_REMOTE=https://opam.ocaml.org KEEP=1
os:
  - linux

