language: c
sudo: required
install: 
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script:
  -bash -ex .travis-ci.sh
  -bash -ex .travis-opam.sh
env:
  matrix:
  - OCAML_VERSION=4.03 OPAM_VERSION=1.2.2 INSTALL=true TESTS=true MERLIN_TRAVIS=true BASE_REMOTE=https://opam.ocaml.org KEEP=1 CONFIGUREFLAGS=--enable-tests


