language: c
sudo: required
install: wget https://rawgithubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: 
  - bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.03 OPAM_VERSION=1.2.2 TESTS=true


